export const SETTINGS_COMMAND_NAMES = new Set([
  'advisor',
  'agents',
  'color',
  'config',
  'config-server',
  'default-model',
  'effort',
  'extra-usage',
  'fast',
  'ide',
  'login',
  'logout',
  'mcp',
  'model',
  'model-list',
  'model-reflex',
  'android',
  'ios',
  'mobile',
  'output-style',
  'permissions',
  'plugin',
  'plugins',
  'pr-comments',
  'privacy-settings',
  'rate-limit-options',
  'remote',
  'remote-env',
  'marketplace',
  'reload-plugins',
  'sandbox',
  'skills',
  'statusline',
  'terminal-setup',
  'theme',
  'vim',
  'update-config',
])

export const AUTOMATION_COMMAND_NAMES = new Set([
  'batch',
  'bashes',
  'install-github-app',
  'install-slack-app',
  'tasks',
  'workflow',
  'workflows',
])

export const COMMAND_CATEGORY: Record<string, string> = {
  clear: '会话',
  compact: '会话',
  context: '会话',
  copy: '会话',
  export: '会话',
  help: '会话',
  rename: '会话',
  resume: '会话',
  session: '会话',
  tag: '会话',
  'add-dir': '上下文',
  files: '本地',
  init: '本地',
  memory: '本地',
  openterminal: '本地',
  branch: 'Git',
  commit: 'Git',
  'commit-push-pr': 'Git',
  diff: 'Git',
  'pr-comments': 'Git',
  rewind: 'Git',
  plan: 'Review',
  review: 'Review',
  'security-review': 'Review',
  ultrareview: 'Review',
  cost: '统计',
  insights: '统计',
  stats: '统计',
  usage: '统计',
  doctor: '支持',
  feedback: '支持',
  'install-github-app': '支持',
  'install-slack-app': '支持',
  'release-notes': '支持',
  upgrade: '支持',
}

export const GUI_SLASH_COMMANDS = [
  ['add-dir', '项目', '新增项目文件夹', true],
  ['agents', '工具', '管理代理配置', false],
  ['branch', 'Git', '从当前会话节点创建分支', true],
  ['btw', '其他', '在不打断主会话的情况下快速提一个旁支问题', true],
  ['clear', '会话', '清空会话历史并释放上下文', false],
  ['color', '外观', '设置本会话提示栏颜色', false],
  ['commit', 'Git', '根据当前改动创建 Git 提交', true],
  ['commit-push-pr', 'Git', '提交、推送并创建或更新 PR', true],
  ['compact', '会话', '清空会话历史但保留上下文摘要。可选：/compact [摘要指令]', true],
  ['config', '设置', '打开主设置', false],
  ['config-server', '设置', '修改项目后端地址', true],
  ['context', '会话', '显示当前上下文使用情况', false],
  ['copy', '会话', '复制 Spark 最近一条回复到剪贴板（或用 /copy N 复制倒数第 N 条）', false],
  ['cost', '统计', '显示当前会话总费用和时长', false],
  ['default-model', '模型', '设置默认模型', false],
  ['desktop', '环境', '确认当前 Spark Code.app 桌面环境', false],
  ['diff', 'Git', '查看未提交变更与每轮差异', false],
  ['doctor', '支持', '诊断并验证 Spark Code 安装状态', false],
  ['effort', '模型', '设置模型使用强度级别', false],
  ['exit', '其他', '退出 Spark Code', false],
  ['export', '会话', '导出当前会话到文件或剪贴板', true],
  ['fast', '模型', '切换快速模式', false],
  ['feedback', '支持', '提交关于 Spark Code 的反馈', true],
  ['files', '本地', '打开当前项目文件浏览与读写面板', true],
  ['help', '会话', '显示帮助与可用命令', false],
  ['ide', '环境', '管理 IDE 集成并显示状态', false],
  ['init', '本地', '初始化新的 SPARK.md 代码库文档', true],
  ['insights', '统计', '生成 Spark Code 会话分析报告', true],
  ['login', '账号', '登录 Spark Code', false],
  ['logout', '账号', '退出 Spark Code', false],
  ['memory', '本地', '编辑 Spark 记忆文件', false],
  ['mcp', '工具', '管理 MCP 服务器', false],
  ['mobile', '远程', '查看移动端和远程控制', false],
  ['model', '模型', '切换当前模型', false],
  ['model-list', '模型', '查看后端可用模型列表', false],
  ['model-reflex', '模型', '配置模型映射别名', true],
  ['openterminal', '本地', '启动网页可访问的 OpenTerminal 本地终端工具', true],
  ['output-style', '外观', '配置输出风格', false],
  ['plan', 'Review', '启用计划模式或查看当前会话计划', true],
  ['permissions', '权限', '管理工具权限', false],
  ['plugin', '工具', '打开插件和工具管理', false],
  ['plugins', '工具', '打开插件和工具管理', false],
  ['pr-comments', 'Git', '获取 GitHub 拉取请求评论', true],
  ['privacy-settings', '账号', '查看并更新隐私设置', false],
  ['rate-limit-options', '统计', '查看达到速率限制时的可选操作', false],
  ['release-notes', '支持', '查看发行说明', false],
  ['reload-plugins', '工具', '刷新插件、Skills 和 MCP 配置', false],
  ['remote', '远程', '配置 Spark Code Remote 远程控制', false],
  ['remote-env', '远程', '配置远程环境', false],
  ['rename', '会话', '重命名当前会话', true],
  ['resume', '会话', '恢复之前的会话', true],
  ['review', 'Review', '审查拉取请求', true],
  ['rewind', 'Git', '将代码和/或对话恢复到之前的时间点', false],
  ['sandbox', '权限', '配置沙箱和权限模式', false],
  ['security-review', 'Review', '对当前分支待提交改动执行安全审查', true],
  ['skills', '工具', '列出可用技能', false],
  ['stats', '统计', '显示 Spark Code 使用统计与活动', false],
  ['status', '其他', '显示 Spark Code 状态', false],
  ['statusline', '外观', '配置状态栏显示', false],
  ['stickers', '其他', '订购 Spark Code 贴纸', false],
  ['tasks', '会话', '列出后台任务与终端输出', false],
  ['terminal-setup', '环境', '配置终端集成', false],
  ['theme', '外观', '更改主题', false],
  ['update-config', '配置', '更新配置文件', false],
  ['upgrade', '账号', '打开 Spark Code 升级页面', false],
  ['usage', '统计', '显示套餐使用限制与本地使用统计', false],
  ['version', '其他', '显示当前 Spark Code 版本', false],
  ['vim', '外观', '切换 Vim 与普通编辑模式设置', false],
] as const

export const GUI_HANDLED_COMMAND_NAMES = new Set([
  'add-dir',
  'agents',
  'branch',
  'btw',
  'clear',
  'color',
  'commit',
  'commit-push-pr',
  'compact',
  'config',
  'config-server',
  'context',
  'copy',
  'cost',
  'default-model',
  'desktop',
  'diff',
  'doctor',
  'effort',
  'exit',
  'export',
  'fast',
  'feedback',
  'files',
  'help',
  'ide',
  'login',
  'logout',
  'memory',
  'mcp',
  'mobile',
  'ios',
  'android',
  'model',
  'model-list',
  'model-reflex',
  'openterminal',
  'open-terminal',
  'output-style',
  'plan',
  'permissions',
  'plugin',
  'plugins',
  'pr-comments',
  'privacy-settings',
  'rate-limit-options',
  'release-notes',
  'reload-plugins',
  'remote',
  'remote-env',
  'rename',
  'resume',
  'review',
  'rewind',
  'sandbox',
  'security-review',
  'skills',
  'stats',
  'status',
  'statusline',
  'stickers',
  'tasks',
  'bashes',
  'terminal-setup',
  'theme',
  'update-config',
  'upgrade',
  'usage',
  'version',
  'vim',
])

export function isSettingsSlashCommand(name: string): boolean {
  return SETTINGS_COMMAND_NAMES.has(name.trim().toLowerCase())
}

export function isAutomationSlashCommand(name: string): boolean {
  return AUTOMATION_COMMAND_NAMES.has(name.trim().toLowerCase())
}

export function isHiddenFromGuiSlashList(command: {
  name: string
  description?: string
  category?: string
  loaded_from?: string
  source?: string
}): boolean {
  if (GUI_HANDLED_COMMAND_NAMES.has(command.name)) return false
  if (command.category === 'Plugin') return true
  if (command.source === 'plugin') return true
  if (command.loaded_from === 'plugin') return true
  if (isSettingsSlashCommand(command.name)) return true
  if (isAutomationSlashCommand(command.name)) return true

  const haystack = `${command.name}\n${command.description ?? ''}\n${command.category ?? ''}`.toLowerCase()
  return (
    haystack.includes('自动化') ||
    haystack.includes('工作流') ||
    haystack.includes('automation') ||
    haystack.includes('workflow')
  )
}
